### ISSUE TITLE
Q about jerk model

### ISSUE THREAD

**Issue by ZhouJY0224** [Aymdi/DeadReckoning#1]
Great article, thank you. Is there any article recommendation about the jerk step detection model?

**Comment by Aymdi** [comment]
Hello, thank you for your feedback :). You can find [here](https://github.com/danielmurray/adaptiv) or in this [article](https://arxiv.org/pdf/1801.02336.pdf) some information that I used for the jerk step detection.

**Comment by ZhouJY0224** [comment]
Hello，thank you for your help:). I start to figure out this model, have a nice day~




Mashiro
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Aymdi/DeadReckoning"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月3日(星期四) 晚上10:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Aymdi/DeadReckoning] Q about jerk model (Issue #1)





 
Hello, thank you for your feedback :). You can find here or in this article some information that I used for the jerk step detection.
