### ISSUE TITLE
fs is not  consistent with the time

### ISSUE THREAD

**Issue by 11721206** [Aymdi/DeadReckoning#3]
1:the time gap in the data you provide  0.01s，ie sample rate is 100Hz, But in deadreckoning.py the fs is 5000Hz?
2:  i use your code, my sample rate is 25ms(40Hz)，the data is generated by app HyperIMU，my tracjectory generated by deadreckoning.py can not match my expectations? Could you tell me some points I should foucs? Thanks !

**Comment by Aymdi** [comment]
Hello, the *fs* in *deadreckoning.py* correspond to the frequency of the low pass filter applied to the sensors data. It has nothing to do with the frequency of data acquisition. You need to modify and adapt the filter requirements depending on the noises you get (order, fs, cutoff). Try using the functions implemented on *plot.py* to display the filter results, so you can see if you found the correct parameters.
For data acquisition, I've used **[Phyphox](https://phyphox.org/)**.

**Comment by 11721206** [comment]
![image](https://user-images.githubusercontent.com/19368412/210693612-3414e557-9a1b-4e25-af82-4d5d6100b74c.png)
hi, when I plot your data and the filtered data, the filtered signal is filtered too seriously  as the figure showed. Is there any reference or papers to tell me why you want to filtered so seriously?Thank You!

**Comment by Aymdi** [comment]
Hello, the main reason to apply such a filter is to smooth the signal and to be able to highlight acceleration peaks and ignore false peaks. I implemented this to be able to count the steps taken during a trajectory for example. You can also change the filters parameters if you want the signal to be filtered less seriously. Here is an [article](https://www.mdpi.com/1424-8220/19/2/294) for more information.
